<a href="https://colab.research.google.com/github/Fredo54/CAP4630/blob/master/HW_5/HW_5_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# General concepts

What is Artificial Intelligence?

Artificial intelligence is very broad with multiple subsets like machine learning and deep learning. Machine Learning and Deep Learning are within AI but AI isn't solely Machine Learning and Deep Learning

What is Machine Learning?

The machine learning process is for a model to modify itself when it is exposed to data. Machine learning does not need any users to run after a model is trained. This is done as the model "learns", hence the name Machine Learning.

What is Deep Learning?

Deep Learning specifies that there are layers in neural networks. Neural networks have many hidden layers that allow them to learn many features of the data without user's supervision. The data structure used are called artifical neural networks. Artificial Neural Networks are done using directed weighted graphs.

# Basic Concepts

What is Linear Regression?

What is so beautiful about linear regression, is that it is simply just y = mx + b. The objective of linear regression is to approximate the equation of a line based on the input data and label values specified. 
Linear regression with multiple weights can be represented as 

y = b + w_1 x_1 + w_2 x_2 + ... + w_n x_n

What is Logistic Regression?

We use logistic regression for binary classificatoin problems. Classifying based on whether the subject is A or B. Logistic regression uses a sigmoid function hat activates within the interval [0, 1] and based on the value being closer to 0 or 1 it will round or truncate to that number.
Sigmoid Function : $\sigma(x)$ = $\frac{1}{1+e^{-x}}$

What are Gradients?

The gradient is a vector where each element in the vector is a partial derivative of a multivariable function.



What is Gradient Descent?

Gradient descent is an implementation of calculating slope to minimize loss.
Calculus allows us to determine the slope throughout the multivariable function. With Machine Learning we take the slope of the loss function with respect to all the weights and try to minimize the total loss of the model. 
By taking the gradient with respect to each weight we can adjust the weights for each directoin and minimize the total loss which improves the model.
The different types of gradient descent we have done are stochastic, batch, and mini-batch.

# Building a Model


What is the structure of a Convent?

Convoltions are operations that involve two inputs. An input matrix, and a kernel or filter are passed. In convolutions the kernel iterates through the columns and rows of the input matrix by a specified length. If the input, kernel, and stride length don't match then the input matrix can be padded with zeros to perform the operation. The kernel iterates and considers each subset of the input matrix. The dot product is done with teh subset of the input matrix and the kernel, then all values are added together with the final value becoming the output matrix.


Max pooling is an operation in which an input matrix and a window size of n by n is specified. The windows iterates throught the input matrix and considers a non overlapping region of n by n. The maximum value in that region becomes one of the values in the output matrix. Padding is allowed if input matrix and window size do not match.



In [0]:
import numpy as np

class invalidInput(Exception):
  print("Error: Input matrix is invalid!")
  exit(1)
  
class invalidKernel(Exception):
  print("Error: Kernel matrix is invalid!")
  exit(1)

  
def conv2d(input_mat, kernel_mat):
  #input_mat = np.matrix(input_mat)
  #kernel_mat = np.matrix(kernel_mat)
  # check for square inputs
  if kernel_mat.shape[0] != kernel_mat.shape[1]:
    raise invalidKernel()
  elif input_mat.shape[0] != input_mat.shape[1]:
    raise invalidInput()
  else:
    # get the dimensions of the output layer
    n = input_mat.shape[0] - kernel_mat.shape[0] + 1
    m = kernel_mat.shape[0]
  

  output_mat = np.zeros((n, n))

  for i in range(n):
    for k in range(n):
      # multiply by kernel filter
      #print(np.multiply(input_mat[i:i+m, k:k+m], kernel_mat))
      #print()
      conv = np.multiply(input_mat[i:i+m, k:k+m], kernel_mat)
      # sum all elements
      output_mat[i,k] = np.sum(conv)

  return output_mat

input_mat = np.array([[1, 2, 1, 2],
                     [2, 1, 2, 1],
                     [1, 2, 1, 2],
                     [2, 1, 2, 1]])

kernel_mat = np.array([[1, 0],
                      [0, 1]])

print(conv2d(input_mat, kernel_mat))

Error: Input matrix is invalid!
Error: Kernel matrix is invalid!
[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]


# Comping a Model


Compiling a model with keras can be done by instantiating a Model and configuring its necessary layers. There are several parameters that should be specified when compiling the model, such as which optimizer instance is needed for training the model.


Loss Function (objective function)
A loss function generates the error of a single training example, and is typically used for minimizing cost with an optimization method such as gradient descent; It is also used as a measure of success for the current task.

The loss functions learned about in this course are:

Squared Error Loss: The square difference between actual and predicted values

$L = (y - f(x))^2$

Binary Cross Entropy Loss: also named Sigmoid Cross-Entropy loss

$L = (Y)(-log(Y_{pred})) + (1-Y)(-log(1-Y_{pred}) $

Learning Rate is typically applied to a gradient to allow for smaller steps toward a minimum of the loss function. If the Learning rate is too small the model can take too long to train or get stuck at a local minimum. If the learning rate is too large the model may overshoot the minimum of the loss function and have a diverging loss. 



Optimizers are used to help the Gradient Descent. They apply different strategies to get faster and more accurate training results.

RMSProp and SGD are popular Optimizers

# Training a Model


Overfitting is when your model performs exceptionally well to your training data but not on the testing data or any new information. This is usually because the model accepts irrevelant information as part of it's algorithm or the "noise" of the data. If the data fits the model too well with low bias and high variance, new data will not be categorized completely.

The fixes for this may be both removing features or training with more data. In the off chance where you capture a specific set of data, more samples may normalize your data. Removing features that are less important will remove more noise from a redundant model.

Underfitting normally results when the model has high loss for both the validation and training data. This can be resolved by either a different learning rate or a more complicated model. It may also be due to the model not being trained long enough.

# Finetuning a pretrained model


Fine tuning is when we take an already trained model and use it to build a new model on a different data set. Companies like Google have trained models that are available to the public. We can download these models and use them and modify them with our own data sets.

When finetuning a pretrained model there are some parts of the model we don't want to affect as they are accurate as is. It is best to freeze many layers that are accurate in a pretrained model like the upper layers. By freezing those layers we can train the bottom layers to get better results on our model.