<a href="https://colab.research.google.com/github/Fredo54/CAP4630/blob/master/HW_1/multiply_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


*   The program takes in a list of arrays.
*   It pops the first 2 arrays and multiplies them.
*   It takes the product of the 2 arrays, appends it to list to continue multiplying
*   When it reaches a failure it prints out the arrays it tried multiplying





In [89]:
import numpy as np

array_1 = np.array(([
                      1, 2
                      ],
                     [
                      2, 1
                      ]))
array_2 = np.array(([
                     3, 4, 3
                     ],
                    [
                     4, 3, 3
                     ]))
array_4 = np.array(([
                     1, 0
                     ],
                    [
                     0, 1
                     ]))
array_5 = np.array(([
                     4, 5
                     ],
                    [
                     6, 7
                     ]))
lst = []
lst.append(array_1)
lst.append(array_2)
lst2 = []
lst2.append(array_4)
lst2.append(array_5)
multiply_matrices(lst)
multiply_matrices(lst2)
def multiply_matrices(
    lst
    ):
  while lst:
    try:
      array_1 = lst.pop()
      array_2 = lst.pop()
      array_3 = np.matmul(array_1, array_2)
      lst.append(array_3)
      if len(lst) == 1:
        print(lst[0])
        print()
        break
    except:
      print("array_1: ")
      print(array_1)
      print("array_2: ")
      print(array_2)
      print("are incompatible")
      print()




array_1: 
[[3 4 3]
 [4 3 3]]
array_2: 
[[1 2]
 [2 1]]
are incompatible

[[4 5]
 [6 7]]

